apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "castellan.fullname" . }}-env
  labels:
    {{- include "castellan.labels" . | nindent 4 }}
data:
  CASTELLAN_DB_NAME: {{ .Values.mongodb.databaseName | quote }}
  CASTELLAN_PORT: {{ .Values.ports.castellan | quote }}
  CASTELLAN_OOBI_PORT: {{ .Values.ports.oobi | quote }}
  CASTELLAN_RACK_PORT: {{ .Values.ports.rack | quote }}
  CASTELLAN_RACK_METRICS_PORT: {{ .Values.ports.rackMetrics | quote }}